### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by wilfried18** [SecUSo/privacy-friendly-torchlight#1]
I am trying to compile this application for the test and use it on my smartphone, how.
Logically I need those to install linux
Thank you

**Comment by p-rack** [comment]
Hi,
if you want to compile the application you could use Android Studio and import the project. Then you can build it via the GUI. You can also build the application from the command line, see https://developer.android.com/tools/building/building-cmdline.html.
Hope that solved your problem!
